name: BuildLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependency
      run: |
        sudo apt-get -y install xorg-dev libglu1-mesa-dev
      
    - name: Run cmake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-9
      
    - name: Build ECSlib
      run: |
        cd build
        cmake --build . --target ECSlib -- -j 4
