name: BuildWindows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.1
      
    - name: Run cmake
      run: |
        mkdir build
        cd build
        cmake ..
      
    - name: Build ECSlib
      run: |
        cd build
        msbuild ECSlib/ECSlib.vcxproj
      
    - name: Build CiopillisClient
      run: |
        cd build
        msbuild CiopillisClient/CiopillisClient.vcxproj
        
    - name: Build CiopillisServer
      run: |
        cd build
        msbuild CiopillisServer/CiopillisServer.vcxproj
